# rbs_inline: enabled
# frozen_string_literal: true

require_relative "node/base"
require_relative "node/after_pop_stack_decl"
require_relative "node/after_reduce_decl"
require_relative "node/after_shift_decl"
require_relative "node/after_shift_error_token_decl"
require_relative "node/before_reduce_decl"
require_relative "node/code_decl"
require_relative "node/define_decl"
require_relative "node/destructor_decl"
require_relative "node/epilogue_decl"
require_relative "node/error_token_decl"
require_relative "node/expect_decl"
require_relative "node/initial_action_decl"
require_relative "node/lex_param_decl"
require_relative "node/locations_decl"
require_relative "node/no_stdlib_decl"
require_relative "node/nterm_decl"
require_relative "node/parameterized_rule"
require_relative "node/parse_param_decl"
require_relative "node/precedence_decl"
require_relative "node/printer_decl"
require_relative "node/prologue_decl"
require_relative "node/require_decl"
require_relative "node/rule"
require_relative "node/rule_rhs"
require_relative "node/start_decl"
require_relative "node/symbol"
require_relative "node/token"
require_relative "node/token_decl"
require_relative "node/type_decl"
require_relative "node/union_decl"
