#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

###### racc/parser.rb begin
unless $".find {|p| p.end_with?('/racc/parser.rb')}
$".push "#{__dir__}/racc/parser.rb"
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
#--
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#++

unless $".find {|p| p.end_with?('/racc/info.rb')}
$".push "#{__dir__}/racc/info.rb"

module Racc
  VERSION   = '1.8.1'
  Version = VERSION
  Copyright = 'Copyright (c) 1999-2006 Minero Aoki'
end

end


module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError # :nodoc:
end

# Racc is an LALR(1) parser generator.
# It is written in Ruby itself, and generates Ruby programs.
#
# == Command-line Reference
#
#     racc [-o<var>filename</var>] [--output-file=<var>filename</var>]
#          [-e<var>rubypath</var>] [--executable=<var>rubypath</var>]
#          [-v] [--verbose]
#          [-O<var>filename</var>] [--log-file=<var>filename</var>]
#          [-g] [--debug]
#          [-E] [--embedded]
#          [-l] [--no-line-convert]
#          [-c] [--line-convert-all]
#          [-a] [--no-omit-actions]
#          [-C] [--check-only]
#          [-S] [--output-status]
#          [--version] [--copyright] [--help] <var>grammarfile</var>
#
# [+grammarfile+]
#   Racc grammar file. Any extension is permitted.
# [-o+outfile+, --output-file=+outfile+]
#   A filename for output. default is <+filename+>.tab.rb
# [-O+filename+, --log-file=+filename+]
#   Place logging output in file +filename+.
#   Default log file name is <+filename+>.output.
# [-e+rubypath+, --executable=+rubypath+]
#   output executable file(mode 755). where +path+ is the Ruby interpreter.
# [-v, --verbose]
#   verbose mode. create +filename+.output file, like yacc's y.output file.
# [-g, --debug]
#   add debug code to parser class. To display debugging information,
#   use this '-g' option and set @yydebug true in parser class.
# [-E, --embedded]
#   Output parser which doesn't need runtime files (racc/parser.rb).
# [-F, --frozen]
#   Output parser which declares frozen_string_literals: true
# [-C, --check-only]
#   Check syntax of racc grammar file and quit.
# [-S, --output-status]
#   Print messages time to time while compiling.
# [-l, --no-line-convert]
#   turns off line number converting.
# [-c, --line-convert-all]
#   Convert line number of actions, inner, header and footer.
# [-a, --no-omit-actions]
#   Call all actions, even if an action is empty.
# [--version]
#   print Racc version and quit.
# [--copyright]
#   Print copyright and quit.
# [--help]
#   Print usage and quit.
#
# == Generating Parser Using Racc
#
# To compile Racc grammar file, simply type:
#
#   $ racc parse.y
#
# This creates Ruby script file "parse.tab.y". The -o option can change the output filename.
#
# == Writing A Racc Grammar File
#
# If you want your own parser, you have to write a grammar file.
# A grammar file contains the name of your parser class, grammar for the parser,
# user code, and anything else.
# When writing a grammar file, yacc's knowledge is helpful.
# If you have not used yacc before, Racc is not too difficult.
#
# Here's an example Racc grammar file.
#
#   class Calcparser
#   rule
#     target: exp { print val[0] }
#
#     exp: exp '+' exp
#        | exp '*' exp
#        | '(' exp ')'
#        | NUMBER
#   end
#
# Racc grammar files resemble yacc files.
# But (of course), this is Ruby code.
# yacc's $$ is the 'result', $0, $1... is
# an array called 'val', and $-1, $-2... is an array called '_values'.
#
# See the {Grammar File Reference}[rdoc-ref:lib/racc/rdoc/grammar.en.rdoc] for
# more information on grammar files.
#
# == Parser
#
# Then you must prepare the parse entry method. There are two types of
# parse methods in Racc, Racc::Parser#do_parse and Racc::Parser#yyparse
#
# Racc::Parser#do_parse is simple.
#
# It's yyparse() of yacc, and Racc::Parser#next_token is yylex().
# This method must returns an array like [TOKENSYMBOL, ITS_VALUE].
# EOF is [false, false].
# (TOKENSYMBOL is a Ruby symbol (taken from String#intern) by default.
# If you want to change this, see the grammar reference.
#
# Racc::Parser#yyparse is little complicated, but useful.
# It does not use Racc::Parser#next_token, instead it gets tokens from any iterator.
#
# For example, <code>yyparse(obj, :scan)</code> causes
# calling +obj#scan+, and you can return tokens by yielding them from +obj#scan+.
#
# == Debugging
#
# When debugging, "-v" or/and the "-g" option is helpful.
#
# "-v" creates verbose log file (.output).
# "-g" creates a "Verbose Parser".
# Verbose Parser prints the internal status when parsing.
# But it's _not_ automatic.
# You must use -g option and set +@yydebug+ to +true+ in order to get output.
# -g option only creates the verbose parser.
#
# === Racc reported syntax error.
#
# Isn't there too many "end"?
# grammar of racc file is changed in v0.10.
#
# Racc does not use '%' mark, while yacc uses huge number of '%' marks..
#
# === Racc reported "XXXX conflicts".
#
# Try "racc -v xxxx.y".
# It causes producing racc's internal log file, xxxx.output.
#
# === Generated parsers does not work correctly
#
# Try "racc -g xxxx.y".
# This command let racc generate "debugging parser".
# Then set @yydebug=true in your parser.
# It produces a working log of your parser.
#
# == Re-distributing Racc runtime
#
# A parser, which is created by Racc, requires the Racc runtime module;
# racc/parser.rb.
#
# Ruby 1.8.x comes with Racc runtime module,
# you need NOT distribute Racc runtime files.
#
# If you want to include the Racc runtime module with your parser.
# This can be done by using '-E' option:
#
#   $ racc -E -omyparser.rb myparser.y
#
# This command creates myparser.rb which `includes' Racc runtime.
# Only you must do is to distribute your parser file (myparser.rb).
#
# Note: parser.rb is ruby license, but your parser is not.
# Your own parser is completely yours.
module Racc

  unless defined?(Racc_No_Extensions)
    Racc_No_Extensions = false # :nodoc:
  end

  class Parser

    Racc_Runtime_Version = ::Racc::VERSION
    Racc_Runtime_Core_Version_R = ::Racc::VERSION

    begin
      if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
        require 'jruby'
        require 'racc/cparse-jruby.jar'
        com.headius.racc.Cparse.new.load(JRuby.runtime, false)
      else
        require 'racc/cparse'
      end

      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extensions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c # :nodoc:
      Racc_YY_Parse_Method         = :_racc_yyparse_c # :nodoc:
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C # :nodoc:
      Racc_Runtime_Type            = 'c' # :nodoc:
    rescue LoadError
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Type            = 'ruby'
    end

    def Parser.racc_runtime_type # :nodoc:
      Racc_Runtime_Type
    end

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    # The entry point of the parser. This method is used with #next_token.
    # If Racc wants to get token (and its value), calls next_token.
    #
    # Example:
    #     def parse
    #       @q = [[1,1],
    #             [2,2],
    #             [3,3],
    #             [false, '$']]
    #       do_parse
    #     end
    #
    #     def next_token
    #       @q.shift
    #     end
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def do_parse
      #{Racc_Main_Parsing_Routine}(_racc_setup(), false)
    end
    RUBY

    # The method to fetch next token.
    # If you use #do_parse method, you must implement #next_token.
    #
    # The format of return value is [TOKEN_SYMBOL, VALUE].
    # +token-symbol+ is represented by Ruby's symbol by default, e.g. :IDENT
    # for 'IDENT'.  ";" (String) for ';'.
    #
    # The final symbol (End of file) must be false.
    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars
      tok = act = i = nil

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    # Another entry point for the parser.
    # If you use this method, you must implement RECEIVER#METHOD_ID method.
    #
    # RECEIVER#METHOD_ID is a method to get next token.
    # It must 'yield' the token, which format is [TOKEN-SYMBOL, VALUE].
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def yyparse(recv, mid)
      #{Racc_YY_Parse_Method}(recv, mid, _racc_setup(), false)
    end
    RUBY

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, _, action_pointer,
      _,            _,            _, _,
      _,            _,            _, shift_n,
      reduce_n,     * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t <= 1 # error token or EOF
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            # We're at EOF, and another error occurred immediately after
            # attempting auto-recovery
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      _,          _,            _,            _,
      goto_table, goto_check,   goto_default, goto_pointer,
      nt_base,    reduce_table, _,            _,
      _,          use_result,   * = arg

      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    # This method is called when a parse error is found.
    #
    # ERROR_TOKEN_ID is an internal ID of token which caused error.
    # You can get string representation of this ID by calling
    # #token_to_str.
    #
    # ERROR_VALUE is a value of error token.
    #
    # value_stack is a stack of symbol values.
    # DO NOT MODIFY this object.
    #
    # This method raises ParseError by default.
    #
    # If this method returns, parsers enter "error recovering mode".
    def on_error(t, val, vstack)
      raise ParseError, sprintf("parse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    # Enter error recovering mode.
    # This method does not call #on_error.
    def yyerror
      throw :racc_jump, 1
    end

    # Exit parser.
    # Return value is +Symbol_Value_Stack[0]+.
    def yyaccept
      throw :racc_jump, 2
    end

    # Leave error recovering mode.
    def yyerrok
      @racc_error_status = 0
    end

    # For debugging output
    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    # Convert internal ID of token symbol to the string.
    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end


require "set"

module Lrama
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 601)

include Lrama::Tracer::Duration

def initialize(text, path, debug = false, define = {})
  @grammar_file = Lrama::Lexer::GrammarFile.new(path, text)
  @yydebug = debug || define.key?('parse.trace')
  @rule_counter = Lrama::Grammar::Counter.new(0)
  @midrule_action_counter = Lrama::Grammar::Counter.new(1)
  @define = define
end

def parse
  report_duration(:parse) do
    @lexer = Lrama::Lexer.new(@grammar_file)
    @grammar = Lrama::Grammar.new(@rule_counter, @define)
    @precedence_number = 0
    reset_precs
    do_parse
    @grammar
  end
end

def next_token
  @lexer.next_token
end

def on_error(error_token_id, error_value, value_stack)
  if error_value.is_a?(Lrama::Lexer::Token)
    location = error_value.location
    value = "'#{error_value.s_value}'"
  else
    location = @lexer.location
    value = error_value.inspect
  end

  error_message = "parse error on value #{value} (#{token_to_str(error_token_id) || '?'})"

  raise_parse_error(error_message, location)
end

def on_action_error(error_message, error_value)
  if error_value.is_a?(Lrama::Lexer::Token)
    location = error_value.location
  else
    location = @lexer.location
  end

  raise_parse_error(error_message, location)
end

private

def reset_precs
  @prec_seen = false
  @code_after_prec = false
end

def begin_c_declaration(end_symbol)
  @lexer.status = :c_declaration
  @lexer.end_symbol = end_symbol
end

def end_c_declaration
  @lexer.status = :initial
  @lexer.end_symbol = nil
end

def begin_lexer_state
  @lexer.status = :lexer_state
end

def end_lexer_state
  @lexer.status = :initial
end

def raise_parse_error(error_message, location)
  raise ParseError, location.generate_error_message(error_message)
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    92,   241,    93,   241,    51,    90,   178,   242,   104,   242,
    51,     6,   190,    82,   104,    43,    51,    51,   178,   190,
   104,   104,   200,   267,   286,   198,   199,    24,    25,    26,
    27,    28,    29,    30,    31,    32,    44,    33,    34,    35,
    36,    37,    38,    39,    40,   246,    90,   268,   287,    47,
   246,   244,   180,    41,   181,    83,   244,   240,   193,   240,
   181,   263,   264,    94,   180,   193,   181,   181,    24,    25,
    26,    27,    28,    29,    30,    31,    32,   262,    33,    34,
    35,    36,    37,    38,    39,    40,   246,   246,   157,   119,
   120,   158,   244,   244,    41,    10,    11,    12,    13,    14,
    15,    16,    17,    18,    48,    24,    25,    26,    27,    28,
    29,    30,    31,    32,    55,    33,    34,    35,    36,    37,
    38,    39,    40,    51,    51,    50,    50,   182,    78,    78,
   158,    41,    10,    11,    12,    13,    14,    15,    16,    17,
    18,    46,    24,    25,    26,    27,    28,    29,    30,    31,
    32,    55,    33,    34,    35,    36,    37,    38,    39,    40,
    51,    51,    50,    50,    55,    78,    78,    51,    41,    50,
    58,   104,    99,    51,     4,    50,     5,   104,    99,    51,
    51,    50,    50,   104,    99,   116,    51,    55,    50,   200,
   104,    99,   198,   199,   132,   200,   266,    55,   198,   199,
   132,   280,    51,    51,    50,    50,   104,   104,    51,    51,
    50,    50,   104,   104,    51,    51,    50,   220,   104,   104,
    51,    51,   220,    50,   104,   104,    51,    55,   220,   231,
   104,   249,   232,   271,   232,     4,   232,     5,    51,    51,
    50,    50,    51,    51,    50,    50,    51,    51,    50,    50,
    51,   185,    50,   186,   185,    51,   186,    50,    51,    55,
    50,    55,    64,    65,    66,    67,    68,    70,    70,    70,
    85,    55,    55,   107,   111,   111,   118,   121,   126,   127,
   129,   132,   133,   137,   143,   144,   145,   148,   149,   151,
   152,   104,   161,   143,   148,   166,   167,   168,   161,   172,
   173,    70,   175,   176,   187,   188,   189,   194,   161,   201,
   132,   205,   208,   209,   210,   211,   161,   213,   132,   161,
   222,   161,   224,   225,   226,   227,   132,    70,   176,   233,
   176,   248,    70,   253,    70,   257,   259,   260,   261,   266,
   132,   246,   277,   278,    70,   282,   283,   264,   285,   288 ]

racc_action_check = [
    49,   225,    49,   237,   160,    47,   160,   225,   160,   237,
   170,     1,   170,    40,   170,     5,   195,   212,   195,   212,
   195,   212,   221,   247,   284,   221,   221,    47,    47,    47,
    47,    47,    47,    47,    47,    47,     6,    47,    47,    47,
    47,    47,    47,    47,    47,   226,    86,   247,   284,     9,
   244,   226,   160,    47,   160,    40,   244,   225,   170,   237,
   170,   243,   243,    49,   195,   212,   195,   212,    86,    86,
    86,    86,    86,    86,    86,    86,    86,   243,    86,    86,
    86,    86,    86,    86,    86,    86,   263,   264,   142,    83,
    83,   142,   263,   264,    86,     3,     3,     3,     3,     3,
     3,     3,     3,     3,    10,     3,     3,     3,     3,     3,
     3,     3,     3,     3,    12,     3,     3,     3,     3,     3,
     3,     3,     3,    36,    37,    36,    37,   163,    36,    37,
   163,     3,     8,     8,     8,     8,     8,     8,     8,     8,
     8,     8,     8,     8,     8,     8,     8,     8,     8,     8,
     8,    13,     8,     8,     8,     8,     8,     8,     8,     8,
    38,    39,    38,    39,    14,    38,    39,    61,     8,    61,
    15,    61,    61,    62,     0,    62,     0,    62,    62,    63,
    76,    63,    76,    63,    63,    76,   100,    16,   100,   177,
   100,   100,   177,   177,   177,   191,   270,    24,   191,   191,
   191,   270,    73,   111,    73,   111,    73,   111,   112,   180,
   112,   180,   112,   180,   193,   201,   193,   201,   193,   201,
   213,   232,   213,   232,   213,   232,   233,    25,   233,   219,
   233,   228,   219,   256,   228,     2,   256,     2,    11,    71,
    11,    71,    78,   107,    78,   107,   108,   114,   108,   114,
   116,   165,   116,   165,   183,   260,   183,   260,   272,    26,
   272,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    42,    53,    58,    69,    72,    74,    82,    84,    87,    88,
    89,    90,    96,   110,   118,   119,   120,   121,   122,   131,
   132,   138,   144,   145,   146,   147,   148,   150,   151,   152,
   153,   157,   158,   159,   166,   167,   169,   174,   176,   178,
   179,   182,   184,   185,   186,   187,   189,   190,   192,   194,
   204,   205,   207,   208,   209,   210,   215,   216,   218,   220,
   223,   227,   229,   230,   231,   236,   238,   239,   242,   245,
   249,   253,   266,   268,   269,   273,   274,   275,   283,   287 ]

racc_action_pointer = [
   161,    11,   222,    79,   nil,     8,    36,   nil,   116,    37,
    98,   235,    61,    98,   111,   165,   134,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   144,   174,   206,   208,   257,   258,
   259,   260,   261,   259,   260,   261,   120,   121,   157,   158,
     8,   nil,   268,   nil,   nil,   nil,   nil,     1,   nil,    -5,
   nil,   nil,   nil,   218,   nil,   nil,   nil,   nil,   219,   nil,
   nil,   164,   170,   176,   nil,   nil,   nil,   nil,   nil,   265,
   nil,   236,   266,   199,   267,   nil,   177,   nil,   239,   nil,
   nil,   nil,   232,    85,   224,   nil,    42,   266,   254,   255,
   215,   nil,   nil,   nil,   nil,   nil,   280,   nil,   nil,   nil,
   183,   nil,   nil,   nil,   nil,   nil,   nil,   240,   243,   nil,
   277,   200,   205,   nil,   244,   nil,   247,   nil,   279,   239,
   242,   232,   274,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   243,   285,   nil,   nil,   nil,   nil,   nil,   284,   nil,
   nil,   nil,    43,   nil,   242,   288,   239,   236,   291,   nil,
   295,   248,   232,   246,   nil,   nil,   nil,   293,   297,   254,
     1,   nil,   nil,    82,   nil,   195,   299,   280,   nil,   257,
     7,   nil,   nil,   nil,   261,   nil,   258,   128,   265,   244,
   206,   nil,   265,   198,   252,   308,   309,   290,   nil,   266,
   273,   134,   252,   211,   269,    13,   nil,   nil,   nil,   nil,
   nil,   212,   nil,   nil,   318,   271,   nil,   268,   270,   267,
   268,   nil,    14,   217,   nil,   260,   319,   nil,   279,   184,
   285,   -39,   nil,   281,   nil,    -4,    40,   326,   186,   324,
   270,   326,   218,   223,   nil,   nil,   281,    -2,   282,   284,
   nil,   nil,   333,    52,    45,   290,   nil,    -2,   nil,   274,
   nil,   nil,   nil,   336,   nil,   nil,   188,   nil,   nil,   nil,
   252,   nil,   nil,    81,    82,   nil,   337,   nil,   338,   336,
   147,   nil,   255,   291,   284,   337,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   343,    -1,   nil,   nil,   344,   nil ]

racc_action_default = [
    -1,  -163,    -1,    -3,   -10,  -163,  -163,    -2,    -3,  -163,
  -163,  -163,  -163,  -163,  -163,  -163,  -163,   -23,   -24,   -25,
   -31,   -32,   -33,   -34,  -163,  -163,  -163,  -163,  -163,  -163,
  -163,  -163,  -163,   -51,   -51,   -51,  -163,  -163,  -163,  -163,
  -163,   -81,  -163,   -13,   289,    -4,   -26,  -163,   -16,  -158,
  -125,  -126,  -157,   -14,   -18,  -117,   -19,   -20,  -163,   -22,
   -35,  -163,  -163,  -163,   -39,   -40,   -41,   -42,   -43,   -44,
   -52,  -163,   -45,  -163,   -46,   -47,  -120,  -122,  -163,   -48,
   -49,   -50,  -163,  -163,  -163,   -11,    -5,    -7,  -127,  -163,
   -69,   -17,  -159,  -160,  -161,   -15,  -163,   -21,   -27,   -28,
   -29,   -36,  -115,  -116,  -162,   -37,   -38,  -163,   -53,   -55,
   -57,  -163,  -111,  -113,  -120,  -121,  -163,  -123,  -163,  -163,
  -163,  -163,  -163,    -6,    -8,    -9,  -155,  -128,  -129,  -130,
   -70,  -163,  -163,  -118,   -30,   -56,   -54,   -58,  -108,  -114,
  -112,  -124,  -163,   -63,   -67,  -163,   -77,  -163,  -163,   -12,
  -163,   -67,  -163,  -163,   -59,  -109,  -110,   -51,  -163,   -61,
   -65,   -68,   -71,  -163,   -78,   -79,  -163,  -163,  -156,  -131,
  -132,  -136,  -154,  -119,  -163,   -64,   -67,   -69,  -125,   -69,
  -163,  -151,  -163,   -79,  -163,  -163,  -163,  -163,   -83,   -67,
  -125,   -69,   -69,  -163,   -67,   -66,   -72,   -73,  -143,  -144,
  -145,  -163,   -75,   -76,  -163,   -67,   -80,  -163,  -163,  -163,
  -163,   -95,  -133,  -163,  -137,   -69,   -51,  -141,   -60,  -163,
  -125,  -146,  -152,   -62,   -82,  -163,   -90,  -163,  -163,   -51,
  -134,   -51,  -163,  -163,  -147,  -148,  -163,   -96,  -163,  -163,
  -102,  -103,  -163,  -163,   -90,   -89,   -92,  -163,   -94,   -69,
  -138,  -135,  -140,   -90,   -74,  -149,  -163,  -153,   -97,   -98,
  -163,  -104,   -84,   -90,   -90,   -88,  -163,   -85,  -163,   -51,
  -163,  -150,   -99,  -163,  -163,   -86,   -87,   -91,   -93,  -139,
  -142,  -100,  -101,  -163,  -163,  -107,  -105,  -163,  -106 ]

racc_goto_table = [
    52,    71,   112,   159,   197,    59,   131,   192,   171,    54,
    56,    57,    87,    60,    61,    62,    63,   115,   215,   117,
    89,   184,   101,   105,   106,    76,    76,    76,    76,   142,
   113,   219,   170,   147,   243,     1,     3,   109,     7,   206,
   112,   112,   238,   228,    72,    74,   171,    97,   234,   192,
    95,   123,   265,   218,   258,   115,   163,   141,   164,    89,
   110,   134,   124,   256,   223,   114,   273,   114,   139,   140,
   212,   275,   276,   135,   136,     9,   125,    42,   281,   122,
    45,    75,    79,    80,    81,    49,    91,    69,   154,   177,
   138,   195,   165,   196,   207,   202,   110,   110,    84,   191,
   247,   270,   284,   114,   155,   114,   156,   214,   216,   203,
    96,   153,   128,   169,   251,   252,   235,   204,   236,   150,
   nil,   nil,   217,   nil,   177,   174,   nil,   nil,   nil,   nil,
   221,   229,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   191,   221,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   255,   221,   nil,   nil,   269,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   230,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   250,   nil,   254,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   279,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   274,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   274 ]

racc_goto_check = [
    30,    28,    21,    34,    37,    14,    41,    39,    40,    16,
    16,    16,     8,    14,    14,    14,    14,    63,    37,    63,
    15,    47,    23,    23,    23,    30,    30,    30,    30,    33,
    60,    38,    67,    46,    49,     1,     6,    29,     6,    47,
    21,    21,    53,    38,    25,    25,    40,    14,    37,    39,
    16,     8,    49,    34,    53,    63,    33,    63,    46,    15,
    30,    23,     5,    38,    34,    30,    56,    30,    60,    60,
    67,    49,    49,    29,    29,     7,     9,    10,    56,    11,
     7,    26,    26,    26,    26,    12,    13,    24,    31,    21,
    32,    35,    43,    41,    45,    41,    30,    30,    48,    21,
    50,    51,    57,    30,    58,    30,    59,    41,    41,    21,
    61,    62,    65,    66,    68,    69,    70,    71,    72,    73,
   nil,   nil,    21,   nil,    21,    28,   nil,   nil,   nil,   nil,
    21,    41,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    21,    21,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    21,    21,   nil,   nil,    41,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    28,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,   nil,    28,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    30,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    30 ]

racc_goto_pointer = [
   nil,    35,   nil,   nil,   nil,   -25,    36,    72,   -35,   -11,
    73,    -6,    74,    37,   -11,   -27,    -3,   nil,   nil,   nil,
   nil,   -71,   nil,   -39,    54,    10,    45,   nil,   -32,   -34,
   -11,   -50,   -20,   -89,  -141,   -85,   nil,  -173,  -170,  -163,
  -143,   -84,   nil,   -55,   nil,   -90,   -88,  -144,    57,  -192,
  -127,  -152,   nil,  -183,   nil,   nil,  -194,  -181,   -34,   -32,
   -43,    55,   -22,   -59,   nil,    24,   -38,  -119,  -116,  -115,
  -105,   -64,  -104,    -7 ]

racc_goto_default = [
   nil,   nil,     2,     8,    86,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    53,    19,   nil,    20,    21,    22,
    23,    98,   100,   nil,   nil,   nil,   nil,   108,    73,   nil,
   102,   nil,   nil,   nil,   nil,   160,   130,   nil,   nil,   179,
   162,   nil,   146,   nil,   183,   nil,   nil,   nil,   nil,   nil,
   nil,   245,   237,   nil,   239,   272,   nil,   nil,   103,   nil,
   nil,   nil,   nil,    77,    88,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 75, :_reduce_1,
  2, 75, :_reduce_2,
  0, 76, :_reduce_3,
  2, 76, :_reduce_4,
  1, 77, :_reduce_5,
  2, 77, :_reduce_6,
  0, 78, :_reduce_none,
  1, 78, :_reduce_none,
  5, 70, :_reduce_none,
  0, 79, :_reduce_10,
  0, 80, :_reduce_11,
  5, 71, :_reduce_12,
  2, 71, :_reduce_13,
  1, 85, :_reduce_14,
  2, 85, :_reduce_15,
  2, 72, :_reduce_16,
  3, 72, :_reduce_17,
  2, 72, :_reduce_none,
  2, 72, :_reduce_19,
  2, 72, :_reduce_20,
  3, 72, :_reduce_21,
  2, 72, :_reduce_22,
  1, 72, :_reduce_23,
  1, 72, :_reduce_24,
  1, 72, :_reduce_none,
  2, 72, :_reduce_none,
  1, 91, :_reduce_27,
  1, 91, :_reduce_28,
  1, 92, :_reduce_29,
  2, 92, :_reduce_30,
  1, 84, :_reduce_none,
  1, 84, :_reduce_none,
  1, 84, :_reduce_none,
  1, 84, :_reduce_none,
  2, 84, :_reduce_35,
  3, 84, :_reduce_36,
  3, 84, :_reduce_37,
  3, 84, :_reduce_38,
  2, 84, :_reduce_39,
  2, 84, :_reduce_40,
  2, 84, :_reduce_41,
  2, 84, :_reduce_42,
  2, 84, :_reduce_43,
  2, 86, :_reduce_none,
  2, 86, :_reduce_45,
  2, 86, :_reduce_46,
  2, 86, :_reduce_47,
  2, 86, :_reduce_48,
  2, 86, :_reduce_49,
  2, 86, :_reduce_50,
  0, 97, :_reduce_none,
  1, 97, :_reduce_none,
  1, 98, :_reduce_53,
  2, 98, :_reduce_54,
  2, 93, :_reduce_55,
  3, 93, :_reduce_56,
  0, 101, :_reduce_none,
  1, 101, :_reduce_none,
  3, 96, :_reduce_59,
  8, 87, :_reduce_60,
  5, 88, :_reduce_61,
  8, 88, :_reduce_62,
  1, 102, :_reduce_63,
  3, 102, :_reduce_64,
  1, 103, :_reduce_65,
  3, 103, :_reduce_66,
  0, 109, :_reduce_none,
  1, 109, :_reduce_none,
  0, 110, :_reduce_none,
  1, 110, :_reduce_none,
  1, 104, :_reduce_71,
  3, 104, :_reduce_72,
  3, 104, :_reduce_73,
  6, 104, :_reduce_74,
  3, 104, :_reduce_75,
  3, 104, :_reduce_76,
  1, 115, :_reduce_77,
  2, 115, :_reduce_78,
  0, 116, :_reduce_79,
  2, 116, :_reduce_80,
  0, 117, :_reduce_81,
  8, 89, :_reduce_82,
  3, 111, :_reduce_83,
  5, 113, :_reduce_84,
  5, 113, :_reduce_85,
  3, 118, :_reduce_86,
  3, 118, :_reduce_87,
  2, 118, :_reduce_88,
  1, 118, :_reduce_none,
  0, 120, :_reduce_none,
  3, 120, :_reduce_91,
  1, 120, :_reduce_92,
  3, 119, :_reduce_93,
  1, 119, :_reduce_94,
  3, 112, :_reduce_95,
  1, 122, :_reduce_96,
  2, 122, :_reduce_97,
  4, 114, :_reduce_98,
  1, 125, :_reduce_99,
  2, 125, :_reduce_100,
  4, 121, :_reduce_101,
  1, 123, :_reduce_102,
  1, 123, :_reduce_103,
  2, 123, :_reduce_104,
  4, 124, :_reduce_105,
  3, 126, :_reduce_106,
  1, 126, :_reduce_107,
  0, 128, :_reduce_none,
  1, 128, :_reduce_none,
  1, 100, :_reduce_110,
  1, 129, :_reduce_111,
  2, 129, :_reduce_112,
  2, 94, :_reduce_113,
  3, 94, :_reduce_114,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  0, 130, :_reduce_117,
  0, 131, :_reduce_118,
  5, 83, :_reduce_119,
  1, 132, :_reduce_120,
  2, 132, :_reduce_121,
  1, 95, :_reduce_122,
  2, 95, :_reduce_123,
  3, 95, :_reduce_124,
  1, 99, :_reduce_125,
  1, 99, :_reduce_126,
  0, 134, :_reduce_none,
  1, 134, :_reduce_none,
  2, 73, :_reduce_none,
  2, 73, :_reduce_none,
  4, 133, :_reduce_131,
  1, 135, :_reduce_132,
  3, 135, :_reduce_133,
  0, 138, :_reduce_none,
  1, 138, :_reduce_none,
  1, 136, :_reduce_136,
  3, 136, :_reduce_137,
  5, 136, :_reduce_138,
  7, 136, :_reduce_139,
  5, 136, :_reduce_140,
  3, 136, :_reduce_141,
  3, 137, :_reduce_142,
  1, 106, :_reduce_143,
  1, 106, :_reduce_144,
  1, 106, :_reduce_145,
  0, 139, :_reduce_none,
  1, 139, :_reduce_none,
  2, 107, :_reduce_148,
  3, 107, :_reduce_149,
  4, 107, :_reduce_150,
  0, 140, :_reduce_151,
  0, 141, :_reduce_152,
  5, 108, :_reduce_153,
  3, 105, :_reduce_154,
  0, 142, :_reduce_155,
  3, 74, :_reduce_156,
  1, 81, :_reduce_none,
  0, 82, :_reduce_none,
  1, 82, :_reduce_none,
  1, 82, :_reduce_none,
  1, 82, :_reduce_none,
  1, 127, :_reduce_162 ]

racc_reduce_n = 163

racc_shift_n = 289

racc_token_table = {
  false => 0,
  :error => 1,
  :C_DECLARATION => 2,
  :CHARACTER => 3,
  :IDENT_COLON => 4,
  :IDENTIFIER => 5,
  :INTEGER => 6,
  :STRING => 7,
  :TAG => 8,
  "||" => 9,
  "&&" => 10,
  "!" => 11,
  "%%" => 12,
  "%{" => 13,
  "%}" => 14,
  "%require" => 15,
  "%expect" => 16,
  "%define" => 17,
  "%param" => 18,
  "%lex-param" => 19,
  "%parse-param" => 20,
  "%code" => 21,
  "%initial-action" => 22,
  "%no-stdlib" => 23,
  "%locations" => 24,
  ";" => 25,
  "%union" => 26,
  "%destructor" => 27,
  "%printer" => 28,
  "%error-token" => 29,
  "%after-shift" => 30,
  "%before-reduce" => 31,
  "%after-reduce" => 32,
  "%after-shift-error-token" => 33,
  "%after-pop-stack" => 34,
  "-temp-group" => 35,
  "%token" => 36,
  "%type" => 37,
  "%nterm" => 38,
  "%left" => 39,
  "%right" => 40,
  "%precedence" => 41,
  "%nonassoc" => 42,
  "%rule" => 43,
  "(" => 44,
  ")" => 45,
  ":" => 46,
  "%inline" => 47,
  "," => 48,
  "|" => 49,
  "%empty" => 50,
  "%prec" => 51,
  "%lexer-state" => 52,
  "{" => 53,
  "}" => 54,
  "state" => 55,
  "predication" => 56,
  "=" => 57,
  "predication_all" => 58,
  "initial_state" => 59,
  "transitions" => 60,
  "*" => 61,
  "=>" => 62,
  "%ls{" => 63,
  "?" => 64,
  "+" => 65,
  "[" => 66,
  "]" => 67,
  "{...}" => 68 }

racc_nt_base = 69

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "C_DECLARATION",
  "CHARACTER",
  "IDENT_COLON",
  "IDENTIFIER",
  "INTEGER",
  "STRING",
  "TAG",
  "\"||\"",
  "\"&&\"",
  "\"!\"",
  "\"%%\"",
  "\"%{\"",
  "\"%}\"",
  "\"%require\"",
  "\"%expect\"",
  "\"%define\"",
  "\"%param\"",
  "\"%lex-param\"",
  "\"%parse-param\"",
  "\"%code\"",
  "\"%initial-action\"",
  "\"%no-stdlib\"",
  "\"%locations\"",
  "\";\"",
  "\"%union\"",
  "\"%destructor\"",
  "\"%printer\"",
  "\"%error-token\"",
  "\"%after-shift\"",
  "\"%before-reduce\"",
  "\"%after-reduce\"",
  "\"%after-shift-error-token\"",
  "\"%after-pop-stack\"",
  "\"-temp-group\"",
  "\"%token\"",
  "\"%type\"",
  "\"%nterm\"",
  "\"%left\"",
  "\"%right\"",
  "\"%precedence\"",
  "\"%nonassoc\"",
  "\"%rule\"",
  "\"(\"",
  "\")\"",
  "\":\"",
  "\"%inline\"",
  "\",\"",
  "\"|\"",
  "\"%empty\"",
  "\"%prec\"",
  "\"%lexer-state\"",
  "\"{\"",
  "\"}\"",
  "\"state\"",
  "\"predication\"",
  "\"=\"",
  "\"predication_all\"",
  "\"initial_state\"",
  "\"transitions\"",
  "\"*\"",
  "\"=>\"",
  "\"%ls{\"",
  "\"?\"",
  "\"+\"",
  "\"[\"",
  "\"]\"",
  "\"{...}\"",
  "$start",
  "input",
  "prologue_declaration",
  "bison_declaration",
  "rules_or_grammar_declaration",
  "epilogue_declaration",
  "\"-many@prologue_declaration\"",
  "\"-many@bison_declaration\"",
  "\"-many1@rules_or_grammar_declaration\"",
  "\"-option@epilogue_declaration\"",
  "@1",
  "@2",
  "variable",
  "value",
  "param",
  "grammar_declaration",
  "\"-many1@param\"",
  "symbol_declaration",
  "rule_declaration",
  "inline_declaration",
  "lexer_state_declaration",
  "symbol",
  "\"-group@symbol|TAG\"",
  "\"-many1@-group@symbol|TAG\"",
  "token_declarations",
  "symbol_declarations",
  "token_declarations_for_precedence",
  "token_declaration",
  "\"-option@TAG\"",
  "\"-many1@token_declaration\"",
  "id",
  "alias",
  "\"-option@INTEGER\"",
  "rule_args",
  "rule_rhs_list",
  "rule_rhs",
  "named_ref",
  "parameterized_suffix",
  "parameterized_args",
  "midrule_action",
  "\"-option@%empty\"",
  "\"-option@named_ref\"",
  "state_declaration",
  "initial_state_declaration",
  "predication_declaration",
  "transitions_declaration",
  "\"-many1@state_declaration\"",
  "\"-many@predication_declaration\"",
  "@3",
  "pattern",
  "all_pattern",
  "pattern_base",
  "transition_declaration",
  "\"-many1@transition_declaration\"",
  "predication",
  "to_state",
  "\"-many1@to_state\"",
  "states",
  "string_as_id",
  "\"-option@string_as_id\"",
  "\"-many1@symbol\"",
  "@4",
  "@5",
  "\"-many1@id\"",
  "rules",
  "\"-option@;\"",
  "rhs_list",
  "rhs",
  "lexer_state_action",
  "\"-option@lexer_state_action\"",
  "\"-option@parameterized_suffix\"",
  "@6",
  "@7",
  "@8" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_1(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_2(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_3(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_4(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_5(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_6(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_10(val, _values, result)
              begin_c_declaration("%}")
          @grammar.prologue_first_lineno = @lexer.line

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_11(val, _values, result)
              end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_12(val, _values, result)
              @grammar.prologue = val[2].s_value

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_13(val, _values, result)
              @grammar.required = true

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_14(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_15(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 38)
  def _reduce_16(val, _values, result)
              @grammar.expect = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_17(val, _values, result)
              @grammar.define[val[1].s_value] = val[2]&.s_value

    result
  end
.,.,

# reduce 18 omitted

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_19(val, _values, result)
              val[1].each {|token|
            @grammar.lex_param = Grammar::Code::NoReferenceCode.new(type: :lex_param, token_code: token).token_code.s_value
          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_20(val, _values, result)
              val[1].each {|token|
            @grammar.parse_param = Grammar::Code::NoReferenceCode.new(type: :parse_param, token_code: token).token_code.s_value
          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_21(val, _values, result)
              @grammar.add_percent_code(id: val[1], code: val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 63)
  def _reduce_22(val, _values, result)
              @grammar.initial_action = Grammar::Code::InitialActionCode.new(type: :initial_action, token_code: val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 67)
  def _reduce_23(val, _values, result)
              @grammar.no_stdlib = true

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_24(val, _values, result)
              @grammar.locations = true

    result
  end
.,.,

# reduce 25 omitted

# reduce 26 omitted

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_27(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_28(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_29(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_30(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

module_eval(<<'.,.,', 'parser.y', 83)
  def _reduce_35(val, _values, result)
              @grammar.set_union(
            Grammar::Code::NoReferenceCode.new(type: :union, token_code: val[1]),
            val[1].line
          )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_36(val, _values, result)
              @grammar.add_destructor(
            ident_or_tags: val[2].flatten,
            token_code: val[1],
            lineno: val[1].line
          )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 98)
  def _reduce_37(val, _values, result)
              @grammar.add_printer(
            ident_or_tags: val[2].flatten,
            token_code: val[1],
            lineno: val[1].line
          )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 106)
  def _reduce_38(val, _values, result)
              @grammar.add_error_token(
            ident_or_tags: val[2].flatten,
            token_code: val[1],
            lineno: val[1].line
          )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 114)
  def _reduce_39(val, _values, result)
              @grammar.after_shift = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 118)
  def _reduce_40(val, _values, result)
              @grammar.before_reduce = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 122)
  def _reduce_41(val, _values, result)
              @grammar.after_reduce = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 126)
  def _reduce_42(val, _values, result)
              @grammar.after_shift_error_token = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 130)
  def _reduce_43(val, _values, result)
              @grammar.after_pop_stack = val[1]

    result
  end
.,.,

# reduce 44 omitted

module_eval(<<'.,.,', 'parser.y', 137)
  def _reduce_45(val, _values, result)
              val[1].each {|hash|
            hash[:tokens].each {|id|
              @grammar.add_type(id: id, tag: hash[:tag])
            }
          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 145)
  def _reduce_46(val, _values, result)
              val[1].each {|hash|
            hash[:tokens].each {|id|
              if @grammar.find_term_by_s_value(id.s_value)
                on_action_error("symbol #{id.s_value} redeclared as a nonterminal", id)
              else
                @grammar.add_type(id: id, tag: hash[:tag])
              end
            }
          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 157)
  def _reduce_47(val, _values, result)
              val[1].each {|hash|
            hash[:tokens].each {|id|
              sym = @grammar.add_term(id: id)
              @grammar.add_left(sym, @precedence_number)
            }
          }
          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 167)
  def _reduce_48(val, _values, result)
              val[1].each {|hash|
            hash[:tokens].each {|id|
              sym = @grammar.add_term(id: id)
              @grammar.add_right(sym, @precedence_number)
            }
          }
          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 177)
  def _reduce_49(val, _values, result)
              val[1].each {|hash|
            hash[:tokens].each {|id|
              sym = @grammar.add_term(id: id)
              @grammar.add_precedence(sym, @precedence_number)
            }
          }
          @precedence_number += 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 187)
  def _reduce_50(val, _values, result)
              val[1].each {|hash|
            hash[:tokens].each {|id|
              sym = @grammar.add_term(id: id)
              @grammar.add_nonassoc(sym, @precedence_number)
            }
          }
          @precedence_number += 1

    result
  end
.,.,

# reduce 51 omitted

# reduce 52 omitted

module_eval(<<'.,.,', 'parser.y', 211)
  def _reduce_53(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 211)
  def _reduce_54(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 199)
  def _reduce_55(val, _values, result)
              val[1].each {|token_declaration|
            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[0], replace: true)
          }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 205)
  def _reduce_56(val, _values, result)
              val[2].each {|token_declaration|
            @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[1], replace: true)
          }

    result
  end
.,.,

# reduce 57 omitted

# reduce 58 omitted

module_eval(<<'.,.,', 'parser.y', 210)
  def _reduce_59(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 215)
  def _reduce_60(val, _values, result)
              rule = Grammar::Parameterized::Rule.new(val[1].s_value, val[3], val[7], tag: val[5])
          @grammar.add_parameterized_rule(rule)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 222)
  def _reduce_61(val, _values, result)
              rule = Grammar::Parameterized::Rule.new(val[2].s_value, [], val[4], is_inline: true)
          @grammar.add_parameterized_rule(rule)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 227)
  def _reduce_62(val, _values, result)
              rule = Grammar::Parameterized::Rule.new(val[2].s_value, val[4], val[7], is_inline: true)
          @grammar.add_parameterized_rule(rule)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 232)
  def _reduce_63(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 233)
  def _reduce_64(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 238)
  def _reduce_65(val, _values, result)
              builder = val[0]
          result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 243)
  def _reduce_66(val, _values, result)
              builder = val[2]
          result = val[0].append(builder)

    result
  end
.,.,

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

module_eval(<<'.,.,', 'parser.y', 250)
  def _reduce_71(val, _values, result)
              reset_precs
          result = Grammar::Parameterized::Rhs.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 255)
  def _reduce_72(val, _values, result)
              token = val[1]
          token.alias_name = val[2]
          builder = val[0]
          builder.symbols << token
          result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 263)
  def _reduce_73(val, _values, result)
              builder = val[0]
          builder.symbols << Lrama::Lexer::Token::InstantiateRule.new(s_value: val[2], location: @lexer.location, args: [val[1]])
          result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 269)
  def _reduce_74(val, _values, result)
              builder = val[0]
          builder.symbols << Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[3], lhs_tag: val[5])
          result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 275)
  def _reduce_75(val, _values, result)
              user_code = val[1]
          user_code.alias_name = val[2]
          builder = val[0]
          builder.user_code = user_code
          result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 283)
  def _reduce_76(val, _values, result)
              sym = @grammar.find_symbol_by_id!(val[2])
          @prec_seen = true
          builder = val[0]
          builder.precedence_sym = sym
          result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 303)
  def _reduce_77(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 303)
  def _reduce_78(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 303)
  def _reduce_79(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 303)
  def _reduce_80(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 293)
  def _reduce_81(val, _values, result)
              begin_lexer_state
          @lexer_state = Grammar::LexerState.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 298)
  def _reduce_82(val, _values, result)
              end_lexer_state
          @grammar.lexer_state = @lexer_state

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 305)
  def _reduce_83(val, _values, result)
              @lexer_state.add_state_bit(val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 311)
  def _reduce_84(val, _values, result)
              @lexer_state.add_predication(val[1], val[3])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 315)
  def _reduce_85(val, _values, result)
              @lexer_state.add_predication(val[1], val[3])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 321)
  def _reduce_86(val, _values, result)
              result = Grammar::LexerState::PatternPredication::OrPattern.new(val[0], val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 325)
  def _reduce_87(val, _values, result)
              result = Grammar::LexerState::PatternPredication::AndPattern.new(val[0], val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 329)
  def _reduce_88(val, _values, result)
              result = Grammar::LexerState::PatternPredication::NotPattern.new(val[1])

    result
  end
.,.,

# reduce 89 omitted

# reduce 90 omitted

module_eval(<<'.,.,', 'parser.y', 336)
  def _reduce_91(val, _values, result)
              state_bit = @lexer_state.find_state_bit!(val[2])
          val[0].add_state_bit(state_bit)
          result = val[0]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 342)
  def _reduce_92(val, _values, result)
              result = @lexer_state.find_pattern!(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 348)
  def _reduce_93(val, _values, result)
              state_bit = @lexer_state.find_state_bit!(val[2])
          val[0].add_state_bit(state_bit)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 353)
  def _reduce_94(val, _values, result)
              state_bit = @lexer_state.find_state_bit!(val[0])
          result = Grammar::LexerState::PatternPredication::AllPattern.new(state_bit)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 360)
  def _reduce_95(val, _values, result)
                @lexer_state.set_initial_state(val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 370)
  def _reduce_96(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 370)
  def _reduce_97(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 366)
  def _reduce_98(val, _values, result)
              result = val[2].flatten

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 378)
  def _reduce_99(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 378)
  def _reduce_100(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 372)
  def _reduce_101(val, _values, result)
              val[2].each do |token, to_state|
            @lexer_state.add_transition(val[0], token, to_state)
          end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 380)
  def _reduce_102(val, _values, result)
              result = Grammar::LexerState::AnyPredication.new

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 384)
  def _reduce_103(val, _values, result)
              result = @lexer_state.find_predication!(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 388)
  def _reduce_104(val, _values, result)
              result = @lexer_state.find_predication!(val[1]).negative_predication

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 394)
  def _reduce_105(val, _values, result)
              result = [val[0], val[2]]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 400)
  def _reduce_106(val, _values, result)
              result = val[0] << @lexer_state.find_state_bit!(val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 404)
  def _reduce_107(val, _values, result)
              result = Set.new([@lexer_state.find_state_bit!(val[0])])

    result
  end
.,.,

# reduce 108 omitted

# reduce 109 omitted

module_eval(<<'.,.,', 'parser.y', 407)
  def _reduce_110(val, _values, result)
     result = val[0].s_value if val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 421)
  def _reduce_111(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 421)
  def _reduce_112(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 412)
  def _reduce_113(val, _values, result)
              result = if val[0]
            [{tag: val[0], tokens: val[1]}]
          else
            [{tag: nil, tokens: val[1]}]
          end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 418)
  def _reduce_114(val, _values, result)
     result = val[0].append({tag: val[1], tokens: val[2]})
    result
  end
.,.,

# reduce 115 omitted

# reduce 116 omitted

module_eval(<<'.,.,', 'parser.y', 427)
  def _reduce_117(val, _values, result)
              begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 431)
  def _reduce_118(val, _values, result)
              end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 435)
  def _reduce_119(val, _values, result)
              result = val[2]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 444)
  def _reduce_120(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 444)
  def _reduce_121(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 439)
  def _reduce_122(val, _values, result)
     result = [{tag: nil, tokens: val[0]}]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 440)
  def _reduce_123(val, _values, result)
     result = [{tag: val[0], tokens: val[1]}]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 441)
  def _reduce_124(val, _values, result)
     result = val[0].append({tag: val[1], tokens: val[2]})
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 444)
  def _reduce_125(val, _values, result)
     on_action_error("ident after %prec", val[0]) if @prec_seen
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 445)
  def _reduce_126(val, _values, result)
     on_action_error("char after %prec", val[0]) if @prec_seen
    result
  end
.,.,

# reduce 127 omitted

# reduce 128 omitted

# reduce 129 omitted

# reduce 130 omitted

module_eval(<<'.,.,', 'parser.y', 454)
  def _reduce_131(val, _values, result)
              lhs = val[0]
          lhs.alias_name = val[1]
          val[3].each do |builder|
            builder.lhs = lhs
            builder.complete_input
            @grammar.add_rule_builder(builder)
          end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 466)
  def _reduce_132(val, _values, result)
              builder = val[0]
          if !builder.line
            builder.line = @lexer.line - 1
          end
          result = [builder]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 474)
  def _reduce_133(val, _values, result)
              builder = val[2]
          if !builder.line
            builder.line = @lexer.line - 1
          end
          result = val[0].append(builder)

    result
  end
.,.,

# reduce 134 omitted

# reduce 135 omitted

module_eval(<<'.,.,', 'parser.y', 484)
  def _reduce_136(val, _values, result)
              reset_precs
          result = @grammar.create_rule_builder(@rule_counter, @midrule_action_counter)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 489)
  def _reduce_137(val, _values, result)
              token = val[1]
          token.alias_name = val[2]
          builder = val[0]
          builder.add_rhs(token)
          result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 497)
  def _reduce_138(val, _values, result)
              token = Lrama::Lexer::Token::InstantiateRule.new(s_value: val[2], alias_name: val[3], location: @lexer.location, args: [val[1]], lhs_tag: val[4])
          builder = val[0]
          builder.add_rhs(token)
          builder.line = val[1].first_line
          result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 505)
  def _reduce_139(val, _values, result)
              token = Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, alias_name: val[5], location: @lexer.location, args: val[3], lhs_tag: val[6])
          builder = val[0]
          builder.add_rhs(token)
          builder.line = val[1].first_line
          result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 513)
  def _reduce_140(val, _values, result)
              user_code = val[1]
          user_code.alias_name = val[2]
          user_code.tag = val[3]
          user_code.lexer_state_action = val[4]
          builder = val[0]
          builder.user_code = user_code
          result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 523)
  def _reduce_141(val, _values, result)
              sym = @grammar.find_symbol_by_id!(val[2])
          @prec_seen = true
          builder = val[0]
          builder.precedence_sym = sym
          result = builder

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 533)
  def _reduce_142(val, _values, result)
              result = val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 537)
  def _reduce_143(val, _values, result)
     result = "option"
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 538)
  def _reduce_144(val, _values, result)
     result = "nonempty_list"
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 539)
  def _reduce_145(val, _values, result)
     result = "list"
    result
  end
.,.,

# reduce 146 omitted

# reduce 147 omitted

module_eval(<<'.,.,', 'parser.y', 544)
  def _reduce_148(val, _values, result)
              result = if val[1]
            [Lrama::Lexer::Token::InstantiateRule.new(s_value: val[1].s_value, location: @lexer.location, args: val[0])]
          else
            [val[0]]
          end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 550)
  def _reduce_149(val, _values, result)
     result = val[0].append(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 551)
  def _reduce_150(val, _values, result)
     result = [Lrama::Lexer::Token::InstantiateRule.new(s_value: val[0].s_value, location: @lexer.location, args: val[2])]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 556)
  def _reduce_151(val, _values, result)
              if @prec_seen
            on_action_error("multiple User_code after %prec", val[0]) if @code_after_prec
            @code_after_prec = true
          end
          begin_c_declaration("}")

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 564)
  def _reduce_152(val, _values, result)
              end_c_declaration

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 568)
  def _reduce_153(val, _values, result)
              result = val[2]

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 571)
  def _reduce_154(val, _values, result)
     result = val[1].s_value
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 576)
  def _reduce_155(val, _values, result)
              begin_c_declaration('\Z')
          @grammar.epilogue_first_lineno = @lexer.line + 1

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 581)
  def _reduce_156(val, _values, result)
              end_c_declaration
          @grammar.epilogue = val[2].s_value

    result
  end
.,.,

# reduce 157 omitted

# reduce 158 omitted

# reduce 159 omitted

# reduce 160 omitted

# reduce 161 omitted

module_eval(<<'.,.,', 'parser.y', 592)
  def _reduce_162(val, _values, result)
     result = Lrama::Lexer::Token::Ident.new(s_value: val[0])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Lrama
